// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"khalif-stories/internal/config"
	"khalif-stories/internal/handler"
	"khalif-stories/internal/repository"
	"khalif-stories/internal/usecase"
)

import (
	_ "khalif-stories/docs"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig := config.LoadConfig()
	db := ProvideDB(configConfig)
	client := ProvideRedis(configConfig)
	categoryRepo := repository.NewCategoryRepository(db)
	redisRepo := repository.NewCacheRepository(client)
	azureUploader := ProvideAzureUploader(configConfig)
	categoryUC := usecase.NewCategoryUseCase(categoryRepo, redisRepo, azureUploader)
	categoryHandler := handler.NewCategoryHandler(categoryUC)
	storyRepo := repository.NewStoryRepository(db)
	storyUseCase := usecase.NewStoryUseCase(configConfig, storyRepo, categoryRepo, redisRepo, azureUploader)
	storyHandler := handler.NewStoryHandler(storyUseCase)
	chapterRepo := repository.NewChapterRepository(db)
	chapterUC := usecase.NewChapterUseCase(configConfig, chapterRepo, storyRepo, azureUploader)
	chapterHandler := handler.NewChapterHandler(chapterUC)
	preferenceRepo := repository.NewPreferenceRepository(db)
	preferenceUC := usecase.NewPreferenceUseCase(preferenceRepo, categoryRepo)
	preferenceHandler := handler.NewPreferenceHandler(preferenceUC)
	app := NewApp(db, client, categoryHandler, storyHandler, chapterHandler, preferenceHandler)
	return app, nil
}
