// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"khalif-stories/internal/config"
	"khalif-stories/internal/handler"
	"khalif-stories/internal/repository"
	"khalif-stories/internal/usecase"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig := config.LoadConfig()
	db := ProvideDB(configConfig)
	client := ProvideRedis(configConfig)
	categoryRepo := repository.NewCategoryRepository(db)
	redisRepo := repository.NewCacheRepository(client)
	azureUploader := ProvideAzureUploader(configConfig)
	categoryUseCase := usecase.NewCategoryUseCase(categoryRepo, redisRepo, azureUploader)
	categoryHandler := handler.NewCategoryHandler(categoryUseCase)
	storyRepo := repository.NewStoryRepository(db)
	storyUseCase := usecase.NewStoryUseCase(storyRepo, redisRepo, azureUploader)
	storyHandler := handler.NewStoryHandler(storyUseCase)
	app := NewApp(db, client, categoryHandler, storyHandler)
	return app, nil
}
