// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
	"khalif-stories/internal/config"
	"khalif-stories/internal/handler"
	"khalif-stories/internal/repository"
	"khalif-stories/internal/usecase"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig := config.LoadConfig()
	db := ProvideDB(configConfig)
	client := ProvideRedis(configConfig)
	storyRepo := repository.NewStoryRepository(db)
	redisRepo := repository.NewCacheRepository(client)
	azureUploader := ProvideAzureUploader(configConfig)
	storyUseCase := usecase.NewStoryUseCase(storyRepo, redisRepo, azureUploader)
	storyHandler := handler.NewStoryHandler(storyUseCase)
	chapterHandler := handler.NewChapterHandler(storyUseCase)
	app := NewApp(db, client, storyHandler, chapterHandler)
	return app, nil
}

// wire.go:

type App struct {
	DB             *gorm.DB
	RDB            *redis.Client
	StoryHandler   *handler.StoryHandler
	ChapterHandler *handler.ChapterHandler
}

func NewApp(db *gorm.DB, rdb *redis.Client, h *handler.StoryHandler, ch *handler.ChapterHandler) *App {
	return &App{
		DB:             db,
		RDB:            rdb,
		StoryHandler:   h,
		ChapterHandler: ch,
	}
}
